### ISSUE TITLE
edit Joly's code for our question

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/pmm#1]
See pmm-pgls-simulations_v2.R and the notes I put at the top...

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @dbuona 

I have been playing a bit with `pmm-pgls-simulations_v2.R` (I have made my own copy of the code: `pmm-pgls-simulations_v2IMC.R`) and changed the function `one.sim.pmm` to change the genetic intraspecific structures by 'star-like' variance-covariance-matrices. Doing this makes models 2 and 3 unhappy, but models 0 and 1 run. I'm not sure we need M.2 and M.3 to work, but I'll continue tomorrow or follow any recs you may have.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Super cool! I see you pushed the code, so I will aim to look at it tonight with Jonathan. Thank you!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 
Please ignore the file called `Pearse-code-4brmsdata.R` for now, I have not started that seriously yet, however, I'm doubtful about how applicable that code is, since it is aimed at predicting presence/absences of species in sites.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Do you get results for any of the models? I ran the code but my res.table is empty and I can't quickly figure out the problem (I also have lost Jonathan -- he needs to record one last lecture -- so will have to pester him for help tomorrow).

But I do agree we can M.2 and M.3, so let's delete those.

Also, if you can see an easy way to write out some of the simulations I could play around with the Pearse code, which probably should be a lower priority. Priority 1 should be getting some simulations running with the pmm-pgls-simulations_v2IMC.R and testing known parameters on brms....

@dbuona has Passover this week so will be less help just now, but I will stand in for him! And Max will join lab meeting so he might have useful perspectives too.

**Comment by lizzieinvancouver** [comment]
More or less done enough I think.
