### ISSUE TITLE
check out math and maybe try changing initial values for ubermini_2.stan

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/pmm#12]
See ubermini_2.R. This relates also to [this issue](https://github.com/lizzieinvancouver/pmm/issues/11) and and  [OSPREE issue 388](https://github.com/lizzieinvancouver/ospree/issues/388) where we can NEVER get the model out of initial value issues. If much preferred you can play with code there (see ../phylogeny/compare_ospreedat_ubermini_2.R).

See 'Cholesky Factors of Covariance Matrices' in the [Stan manual](https://mc-stan.org/docs/2_19/reference-manual/cholesky-factors-of-covariance-matrices-1.html))

And one maybe or maybe not useful post from Stan Discourse:

"..it is not really a bug, just a numerical problem. You could also do init_r = some number less than the default of 2." [here](https://discourse.mc-stan.org/t/cholesky-factor-corr-initializing-with-invalid-values/3167)

@FaithJones to keep us cross-referenced!

**Comment by lizzieinvancouver** [comment]
@legault Hello! I'd like to roll this rock a little further down its path this week -- any updates on this?

**Comment by legault** [comment]
See commit e6fabd54a874f5535e32caae59f0b1c8ede97258 for a fix to the vcv function, sig2, and adding a prior to sigma_y. This addresses some of the modeling issues such that we now correctly infer the parameter values in ubermini_2.R

The Cholesky decomp may no longer be necessary.

**Comment by lizzieinvancouver** [comment]
@legault Thanks for this, but the issue wasn't about the vcv, are you sure it was wrong? Can you provide a little more details on what was wrong (and thus what you fixed here)? I'd like to understand and it's not so clear what errors you found in the math from your notes and the commit.

**Comment by legault** [comment]
I shouldn't have said "fix" as all I did was re-specify things using sigma instead variance (in vcv). Commit d85d59e has some additional changes, notably the addition of a function that sets initial values which avoid the numerical issues we've been seeing.

**Comment by lizzieinvancouver** [comment]
@legault's commit mentioned above seems to have solved the initial conditions issue. Yay!

**Comment by lizzieinvancouver** [comment]
A few more notes what happened here (from an email from @legault on 20 Nov 2020):

> - I rewrote the vcv function so that it uses standard deviation instead of variance. I didn't make the connection that sig2 meant sigma ^ 2 (i.e., variance). I also rewrote the function so that it creates the covariance matrix using the associated variance matrix and correlation matrix as opposed to multiplying a matrix by a constant (they're equivalent though, apparently).
> -- Interestingly, the newer version seems to be more efficient (i.e., fewer iterations to obtain a good set of samples). I don't know why exactly but it might be a numerical issue (e.g., easier to work with x than it is to work with x^2)
> 
> - I added a prior for sigma_y in the model block
> 
> I will likely revert the changes to keep things organized as before. From working with the previous version, I can't tell what the problem is. Is there an issue beyond the messages that pop up during initialization? The estimates seem ok if you run things long enough.
