### ISSUE TITLE
what to assign others to prep for lab meeting (15 April)

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/pmm#3]
@MoralesCastilla @dbuona For now I was going to suggest:

* Everyone read Housworth et al. 2004. 
* Folks who want some background can read Chapter one [here](https://books.google.ca/books/about/Modern_Phylogenetic_Comparative_Methods.html?id=s-YkBAAAQBAJ) and maybe Chapter 11 (UBC has it online) ... @dbuona Are those good chapters?
* If I have time this weekend I will add some simple code for folks to run.
* I will also suggest the Joly intro to PMM (half a page) 
* Should we also suggest the brms vignette through repeated measures?
* What else? 

Let me know your thoughts! I will try to get out an email on Thursday. This is just to assign others -- I am hoping that @MoralesCastilla and I will have some code to walk though, *maybe* some insights and we can work towards next steps! 

Thank you both!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 

These are great suggestions. My only additional suggestion has to do with running code. I imagine you have thought about this already, but it would be great if each person could simulate data with different sets of parameters (e.g. number of species, number of individuals within species including balanced and unbalanced scenarios, strengths of the associations between x and y, linear and non-linear relationships between x and y, etc.) and then compare results by using mcmcPGLMM and BRMS with the species-level centering of data. Each person could then fill in a csv table with results and the parameters used (as we've done multiple times), so we can have a better grasp of what is going on in our next meeting.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla That's a great idea (I had not thought of it so thanks for suggesting). Thanks for setting it up!
