### ISSUE TITLE
run models and compare results

### ISSUE THREAD

**Issue by MoralesCastilla** [lizzieinvancouver/pmm#4]
@lizzieinvancouver @dbuona 

This issue would concern everyone involved. The aim is to start filling a model comparison table [PMM_models_comparison.csv](https://github.com/lizzieinvancouver/pmm/blob/master/analyses/output/PMM_models_comparison.csv) with results from fitting MCMCglmm, PGLS, BRMS (and Pearse's? - TBD) models. Each participating person can modify the code `analyses/run_MCMCpglmm.R` to change parameters, save their own version to avoid conflicts (e.g. run_MCMCpglmm_imc.R), run it, and then copy the results to the model comparison .csv.

Things still needed:
1) We should decide what combinations of parameters we are interested in, e.g.:
- nsps = 50; nindiv = 15; B = 0.25; sigma.sq.x = 2; sigma.sq.p = 1; sigma.sq.c = 1; sigma.sq.e = 1
- nsps = 50; nindiv = 15; B = 0.5; sigma.sq.x = 2; sigma.sq.p = 1; sigma.sq.c = 1; sigma.sq.e = 1
- nsps = 50; nindiv = 15; B = 0.75; sigma.sq.x = 2; sigma.sq.p = 1; sigma.sq.c = 1; sigma.sq.e = 1
- etc.

2) How many replications for each subset of parameters? We can recicle Joly's code to parallelize processing, but I have not done that yet.

Once we have a reasonable list of parameters subsets, people could sign up in the .csv, run the models and fill in their results.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla set.seed will work! The only trick is making sure it's everyone's first run (or if we want them to do multiple trees, we have to all stay on the same first, or second or third draw). Does that make sense? You can try it out and see what I mean.

**Comment by lizzieinvancouver** [comment]
I ran some checks in the fall and it looked good, we could always run more, but okay for now.
