### ISSUE TITLE
Why cant i use the code to extract model results if there are divergent transitions?

### ISSUE THREAD

**Issue by FaithJones** [lizzieinvancouver/pmm#6]
I have divergent transitions in the brms models, but the code at the bottom to extract values seems to be working fine. Why do I need to extract the results manually in this case?

**Comment by lizzieinvancouver** [comment]
@FaithJones Ah, sorry for the confusion. I just meant you have to write down how many divergent transitions you got in the csv. All the other results should be fine and do not need to be manually extracted. Please close if that makes sense!
