### ISSUE TITLE
check my matrix code matches stan ... 

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/pmm#9]
Step 1) Check that my code in ubertoy_nogeiger.R, especially this line 35:

`slopez <- mvrnorm(n=1, mu=rep(0, nspecies), Sigma=(diag(rep(null_interceptsb, nspecies)) + lam_interceptsb*Vphy))
`
matches the Stan code in ubermini.stan, especially this:

`b_force ~ multi_normal(rep_vector(0,n_sp), diag_matrix(rep_vector(null_interceptsb, n_sp)) + lam_interceptsb*Vphy); 
`

Step 2) Maybe try to figure out why this is not the same as what fastBM does. I mean, spend a short while on this and no longer! I did ask JD and he said fastBM is just an analytical expectation so I looked into the code for it, [see here](https://rdrr.io/cran/phytools/src/R/fastBM.R) and I think it's doing something very different than us.

**Comment by lizzieinvancouver** [comment]
ubertoy.R has what is supposed to the equivalent code of ubertoy_nogeiger.R except using geiger.

**Comment by legault** [comment]
Code has been checked: the two lines (R versus Stan) produce the same output.
